### ISSUE TITLE
Comparison function wrong?

### ISSUE THREAD

**Issue by sergi-gonzalez** [aaronscherzinger/polygonnesting#1]
https://github.com/aaronscherzinger/polygonnesting/blob/2da12c838e38ebea16ca65cdbeb6d79081bc30fc/polygonnesting.h#L564 I think that you should use GetY when x has the same value. I think there is a bug here according to your comments. I didn't test the code though.

**Comment by aaronscherzinger** [comment]
Sorry for the late reply, I overlooked your comment - you are of course right! I fixed the bug, thanks a lot for reporting this.
